name: Deploy to Azure App Service

on:
  push:
    branches:
      - main # หรือ branch ที่คุณต้องการ deploy
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # หรือเวอร์ชันที่โปรเจกต์ของคุณใช้

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: <YOUR_APP_NAME> # ชื่อแอปพลิเคชัน Azure App Service ของคุณ
        slot-name: 'production' # ถ้ามีการใช้ slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # ตั้งค่าใน GitHub Secrets
        package: .