name: Deploy WebApp to azure

env:
    AZURE_WEBAPP_NAME: pitak-web-app

on:
  push:
    branches:
      - main # หรือ branch ที่คุณต้องการ deploy
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }} # หรือเวอร์ชันที่โปรเจกต์ของคุณใช้

    - name: npm install, build
      run:  npm install

    - name: Package and upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: $ {{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  
